modLoader="javafml"
loaderVersion="[42,)"
license="All rights reserved"
[[mods]] 
modId="agrigrowth"
version="${file.jarVersion}"
displayName="AgriGrowth"
description='''
Growing tool for AgriCraft
'''
[[dependencies.agrigrowth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.agrigrowth]]
    modId="agricraft"
    mandatory=false
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.agrigrowth]]
    modId="mysticalagriculture"
    mandatory=false
    versionRange="[6.0.0,)"
    ordering="NONE"
    side="BOTH"
