modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]] 
modId="agrigrowth"
version="${file.jarVersion}"
displayName="AgriGrowth"
description='''
Growing tool for AgriCraft
'''
[[dependencies.agrigrowth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.agrigrowth]]
    modId="agricraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
