modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]] 
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''
[[dependencies.agrigrowth]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.agrigrowth]]
    modId="agricraft"
    mandatory=false
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.agrigrowth]]
    modId="mysticalagriculture"
    mandatory=false
    versionRange="[7.0.0,)"
    ordering="NONE"
    side="BOTH"
